image: node:20

stages: [deploy]

variables:
  PNPM_HOME: /root/.local/share/pnpm
  PATH: $PNPM_HOME:$PATH
  NODE_ENV: production

before_script:
  - corepack enable
  - pnpm install --frozen-lockfile

pages:                        # Pages 必须叫 pages
  stage: deploy
  script:
    - BASE_PATH=/apps/vue-demo/   pnpm --filter ./web/vue-demo   build
    - BASE_PATH=/apps/react-demo/ pnpm --filter ./web/react-demo build
    - pnpm --filter ./main build
    - mkdir -p public/apps/vue-demo public/apps/react-demo
    - cp -r main/dist/*            public/
    - cp -r web/vue-demo/dist/*    public/apps/vue-demo/
    - cp -r web/react-demo/dist/*  public/apps/react-demo/
    - printf '%s\n' '{ "vue-demo": { "url": "/apps/vue-demo/" }, "react-demo": { "url": "/apps/react-demo/" } }' > public/micro-apps.json
  artifacts:
    paths:
      - public
  only:
    - main
    - master
